<?php require_once("cnet-header.php"); ?>

<h1><i>cnet</i>'s Application Programming Interface</h1>

<dl>

<dt>NAME</dt>
<dd>CNET_write_application - present a new message to the Application Layer
<p>
</dd>


<dt>SYNOPSIS</dt>
<dd>
<div class="code">
#include &lt;cnet.h&gt;

<b>int</b> CNET_write_application(<b>const void</b> *message, size_t *length);
</div>
<p>
</dd>


<dt>DESCRIPTION</dt>
<dd>
<code>CNET_write_application</code>
passes a number of bytes,
pointed to by <code>message</code>, "up to" the Application Layer.
It is expected that the contents of <code>message</code> will be exactly that
generated by, and delivered for, another node's Application Layer.
</p>

<p>
On invocation, <code>length</code> must point to an integer indicating the number
of bytes to be copied from <code>message</code>.
</p>

<p>
On return, <code>length</code> will point to an integer now indicating the number
of bytes accepted by the Application Layer.
</p>
</dd>

<dt>RETURN VALUE</dt>
<dd>
The value <code>0</code> is returned on success.
On failure, the value <code>-1</code> is returned,
and the global variable <code>cnet_errno</code> is set to one of the
following values to describe the error:
</p>

<p>
<dl>
<dt><code>ER_BADARG</code></dt>
    <dd>Either <code>message</code> or <code>length</code> is an invalid pointer,
    or the value provided by <code>length</code> is less <code>0</code> or
    greater than  <code>MAX_MESSAGE_SIZE</code>.

</dd>

<dt><code>ER_BADSENDER</code></dt>
    <dd>The message has not been generated by another node's Application
	Layer (and a node cannot write a message to itself).
</dd>

<dt><code>ER_BADSESSION</code></dt>
    <dd>Either the source node, or the current node, have crashed and
	rebooted since the message was generated.
</dd>

<dt><code>ER_BADSIZE</code></dt>
    <dd>The message is not the same length as the original message
	generated by another node's Application Layer.
</dd>

<dt><code>ER_CORRUPTFRAME</code></dt>
    <dd>The contents of the message are not the same as the original message
	generated by another node's Application Layer.
</dd>

<dt><code>ER_DUPLICATEMSG</code></dt>
    <dd>The message has already been seen by the Application Layer
	(for example, if the messages from another node are presented in the
	order first, second, second,...).
</dd>

<dt><code>ER_MISSINGMSG</code></dt>
    <dd>The message is being delivered out of order with respect to all
	previously received messages from the message's source node
	(for example, if the messages are presented in the order
	first, second, fourth,...).
</dd>

<dt><code>ER_NOTFORME</code></dt>
    <dd>The message has been written to the incorrect node's Application Layer.
</dd>

<dt><code>ER_NOTSUPPORTED</code></dt>
    <dd>The current node does not have an Application Layer.
</dd>

</dl>
</dd>

<dt>SEE ALSO</dt>
<dd>
<a href="api_read_application.php">CNET_read_application</a>
</dd>

</dl>

<?php require_once("cnet-footer.php"); ?>
