<?php require_once("cnet-header.php"); ?>

<h1 id="datastructures"><i>cnet</i>'s core data structures</h1>

<p>
<i>cnet's</i> provides a number of core data structures,
each defined in the <code>&lt;cnet.h&gt;</code> header file.
Each node has access to <i>its own instance</i> of these data structures.
The data structures are:
</p>

<ul>
<li> the <a href="#nodeinfo"><code>nodeinfo</code></a> data structure
<li> the <a href="#linkinfo"><code>linkinfo</code></a> data structure
</ul>

<p></p>

<h1 id="nodeinfo">The <code>nodeinfo</code> data structure</h1>

<p>
Each node's attributes may be accessed with,
for example,
<code>if(nodeinfo.nlinks&nbsp;&gt;&nbsp;1)&nbsp;...</code>
</p>

<table class="thin" style="width: 100%;">

<tr>
    <th class="thin">datatype</th>
    <th class="thin">fieldname</th>
    <th class="thin">meaning</th>
</tr>

<tr>
    <td class="option0">CnetNodeType</td>
    <td class="option0">nodetype</td>
    <td class="option0">one of NT_HOST, NT_ROUTER, NT_MOBILE, or NT_ACCESSPOINT</td>
</tr>

<tr>
    <td class="option1">int</td>
    <td class="option1">nodenumber</td>
    <td class="option1">this node's unique number, from 0 .. number_of_nodes-1</td>
</tr>
<tr>
    <td class="option0">CnetAddr</td>
    <td class="option0">address</td>
    <td class="option0">this node's unique address</td>
</tr>

<tr>
    <td class="option1">char array</td>
    <td class="option1">nodename</td>
    <td class="option1">this node's unique name, a nul-byte terminated string
	such as <i>host3</i> or <i>Perth</i></td>
</tr>
<tr>
    <td class="option0">int</td>
    <td class="option0">nlinks</td>
    <td class="option0">this node's number of physical links, &ge; 1</td>
</tr>

<tr>
    <td class="option1">CnetTime</td>
    <td class="option1">time_in_usec</td>
    <td class="option1">the number of microseconds since this node last rebooted</td>
</tr>
<tr>
    <td class="option0">structure of 2 ints</td>
    <td class="option0">time_of_day</td>
    <td class="option0">this node's "wall clock" time,
    with subfields <code>time_of_day.secs</code> and <code>time_of_day.usec</code></td>
</tr>

<tr>
    <td class="option1">CnetTime</td>
    <td class="option1">messagerate</td>
    <td class="option1">the rate (in microseconds) at which this node's Application Layer
	generates new messages</td>
</tr>
<tr>
    <td class="option0">int</td>
    <td class="option0">minmessagesize</td>
    <td class="option0">the minimum sized message to be generated by this node's Application Layer</td>
</tr>

<tr>
    <td class="option1">int</td>
    <td class="option1">maxmessagesize</td>
    <td class="option1">the maximum sized message to be generated by this node's Application Layer</td>
</tr>
</table>

<p></p>

<h1 id="lininfo">The <code>linkinfo</code> data structure</h1>

<p>
The attributes of
each node's links may be accessed via fields in the <code>linkinfo</code> data
structure.
<code>linkinfo</code> is an array,
of type <code>LinkInfo</code>,
indexed by the required link number.
Link numbers commence at 0 (for the <code>LT_LOOPBACK</code> link);
the first "true", physical link has the index 1.
</p>

<p>
Each link's attributes may be accessed with,
for example,
<code>if(linkinfo[1].linkup)&nbsp;...</code>
</p>

<table class="thin" style="width: 100%;">

<tr>
    <th class="thin">datatype</th>
    <th class="thin">fieldname</th>
    <th class="thin">meaning</th>
</tr>
<tr>
    <td class="option0">CnetLinkType</td>
    <td class="option0">linktype</td>
    <td class="option0">one of LT_LOOPBACK, LT_WAN, LT_LAN, or LT_WLAN</td>
</tr>

<tr>
    <td class="option1">char array</td>
    <td class="option1">linkname</td>
    <td class="option1">this link's unique name, a nul-byte terminated string such as
	<i>lan1</i> or <i>wlan0</i></td>
</tr>
<tr>
    <td class="option0">bool</td>
    <td class="option0">linkup</td>
    <td class="option0">true iff this link is up and functioning correctly</td>
</tr>

<tr>
    <td class="option1">CnetNICaddr</td>
    <td class="option1">nicaddr</td>
    <td class="option1">this link's network interface card's (NIC's) address</td>
</tr>
<tr>
    <td class="option0">int</td>
    <td class="option0">bandwidth</td>
    <td class="option0">this link's bandwidth, in bits per second</td>
</tr>

<tr>
    <td class="option1">int</td>
    <td class="option1">mtu</td>
    <td class="option1">this link's maximum transmission unit (MTU) in bytes</td>
</tr>
<tr>
    <td class="option0">CnetTime</td>
    <td class="option0">propagationdelay</td>
    <td class="option0">the propagation delay (in microseconds) along this link,
	iff a LT_WAN or LT_LAN link</td>
</tr>

<tr>
    <td class="option1">int</td>
    <td class="option1">costperbyte</td>
    <td class="option1">the (unitless) cost of transmitting each byte on this link</td>
</tr>
<tr>
    <td class="option0">int</td>
    <td class="option0">costperframe</td>
    <td class="option0">the (unitless) cost of transmitting each frame on this link</td>
</tr>
</table>

<?php require_once("cnet-footer.php"); ?>
